# Site settings
title: 'Loiane Groner'
title_separator: "|"
description: > # this means to ignore newlines until "baseurl:"
  Java, Angular, Sencha, JavaScript, Phonegap
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url: "http://loiane.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
twitter_username: loiane
github_username:  loiane
include: [_pages]
exclude: ['node_modules']
paginate: 12
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true
encoding: "utf-8"

# Build settings
markdown: kramdown
highlighter: rouge

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Gems
plugins: [jekyll-paginate]
